language: go

go:
  - 1.12.1

before_install:
  - go get github.com/tools/godep
  - godep restore

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGPORT=5433

before_script:
  - psql -c 'create database test; \c test; create table fict_sensors_syn
    (
    id           serial primary key,
    id_sensor    integer   not null,
    value_sensor float(2)  not null,
    time_add     timestamp not null
    );insert into fict_sensors_syn(id_sensor, value_sensor, time_add)VALUES (1, 1, now()),
    (1, 2, now() - '1 day'::INTERVAL),
    (1, 3, now() - '2 day'::INTERVAL),
    (1, 4, now() - '3 day'::INTERVAL),
    (1, 5, now() - '4 day'::INTERVAL),
    (2, 10, now() - '2 day'::INTERVAL),
    (2, 11, now() - '3 day'::INTERVAL),
    (2, 12, now() - '4 day'::INTERVAL),
    (2, 13, now() - '5 day'::INTERVAL),
    (2, 14, now() - '6 day'::INTERVAL),
    (2, 15, now() - '7 day'::INTERVAL);' -U postgres

script:
  - go test ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) CODECOV_TOKEN
