notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

language: go

go:
  - 1.12.1

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_install:
  - go get github.com/tools/godep
  - godep restore
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1

env:
  global:
    - PGPORT=5433

before_script:
  - psql -c 'create database test;' -U postgres

script:
  - go test ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) CODECOV_TOKEN
